-- FireReach development seed. GENERATED by seeds/build_seed.py.
-- Do not edit by hand; re-run the generator instead.
--
-- Coordinates + names : OpenStreetMap (ODbL), amenity=fire_station
-- Region + district   : OSM Nominatim reverse geocoding (ODbL)
-- Contact numbers     : GNFS official contact-numbers page,
--                       archived 2022-08-09
--
-- CAVEATS
--   response_rate encodes PUBLICATION ORDER, not measured
--   reliability. No GNFS response-rate data is published. The
--   field name overstates what these values mean.
--
--   EXCEPTION: for Northern-region stations, the order above is
--   deliberately inverted relative to the source page, because the
--   source's first-listed number (0322022864) uses a Kumasi/
--   Ashanti telephone prefix rather than Tamale's, and is disputed
--   by an independent aggregator. See the DISCREPANCY comment next
--   to GNFS_COMMANDS['northern'] in build_seed.py for detail.
--
--   Contact numbers are regional command lines, not per-station
--   direct lines, and were archived in 2022.
--
--   NOT VERIFIED FOR EMERGENCY USE. Confirm every number directly
--   with GNFS before any production deployment.
--
-- LICENSE: this file is Open Database License (ODbL) v1.0,
--   separately from the rest of this repository, which is
--   AGPL-3.0-or-later. See LICENSE-DATA at the repo root. ODbL
--   share-alike passes to derived databases and cannot be
--   narrowed by the surrounding code license, so the split is
--   required rather than preferred.
--
--   Contains information from OpenStreetMap, which is made
--   available under the Open Database License (ODbL) v1.0.
--   (c) OpenStreetMap contributors
--   https://www.openstreetmap.org/copyright

BEGIN;

DELETE FROM submissions WHERE station_id IS NOT NULL;
DELETE FROM station_contacts;
DELETE FROM stations;

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('d5599159-1077-549b-b632-60da77e0aa90', 'Abelemkpe Fire Station', 'Greater Accra Region', 'Ayawaso West Municipal District', 5.6090978, -0.2111861, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('d5599159-1077-549b-b632-60da77e0aa90', '0302666576', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('d5599159-1077-549b-b632-60da77e0aa90', '0299346018', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('d5599159-1077-549b-b632-60da77e0aa90', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('efc7d1b5-dd07-5ad9-bccd-f45633507a76', 'Accra City Fire Station', 'Greater Accra Region', 'Accra Metropolitan District', 5.5493054, -0.2073036, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('efc7d1b5-dd07-5ad9-bccd-f45633507a76', '0302666576', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('efc7d1b5-dd07-5ad9-bccd-f45633507a76', '0299346018', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('efc7d1b5-dd07-5ad9-bccd-f45633507a76', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('0eb0ab4d-8a8f-5ca9-b348-f9e824eaaa6e', 'Airport Fire Station', 'Greater Accra Region', 'La-Dade-Kotopon Municipal District', 5.6037167, -0.1725827, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('0eb0ab4d-8a8f-5ca9-b348-f9e824eaaa6e', '0302666576', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('0eb0ab4d-8a8f-5ca9-b348-f9e824eaaa6e', '0299346018', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('0eb0ab4d-8a8f-5ca9-b348-f9e824eaaa6e', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('dfbebb39-38ed-5a8b-ad6d-35223ef8cb09', 'Akatsi Fire Station', 'Volta Region', 'Akatsi South District', 6.1192567, 0.8080749, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('dfbebb39-38ed-5a8b-ad6d-35223ef8cb09', '0362026679', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('dfbebb39-38ed-5a8b-ad6d-35223ef8cb09', '0299346042', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('dfbebb39-38ed-5a8b-ad6d-35223ef8cb09', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('47f5ca79-de8b-5cc2-ae6f-80de6f9ad4d2', 'Amamoley Fire Station', 'Greater Accra Region', 'Ga North Municipal District', 5.6623707, -0.2971575, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('47f5ca79-de8b-5cc2-ae6f-80de6f9ad4d2', '0302666576', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('47f5ca79-de8b-5cc2-ae6f-80de6f9ad4d2', '0299346018', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('47f5ca79-de8b-5cc2-ae6f-80de6f9ad4d2', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('e4fd5ba6-cd50-50e6-ad9e-015fb954fabb', 'Asante-Akim Central Fire Station', 'Ashanti Region', 'Asante-Akim Central Municipal District', 6.6216556, -1.2225636, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('e4fd5ba6-cd50-50e6-ad9e-015fb954fabb', '0322022221', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('e4fd5ba6-cd50-50e6-ad9e-015fb954fabb', '0299346044', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('e4fd5ba6-cd50-50e6-ad9e-015fb954fabb', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('7a65a5be-45e2-584b-8c8e-f01dfdf4675e', 'Cape Coast Fire Service', 'Central Region', 'Cape Coast Metropolitan District', 5.1112215, -1.2481432, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('7a65a5be-45e2-584b-8c8e-f01dfdf4675e', '0332132902', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('7a65a5be-45e2-584b-8c8e-f01dfdf4675e', '0299340499', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('7a65a5be-45e2-584b-8c8e-f01dfdf4675e', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('5ef46b09-d045-5e8a-b6eb-5cee1d6251bf', 'Dambai Fire Station', 'Oti Region', 'Krachi East District', 8.0539235, 0.1861614, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('5ef46b09-d045-5e8a-b6eb-5cee1d6251bf', '0362026679', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('5ef46b09-d045-5e8a-b6eb-5cee1d6251bf', '0299346042', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('5ef46b09-d045-5e8a-b6eb-5cee1d6251bf', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('5e897d40-540f-5f8f-a3a2-eb4c52f6ff48', 'Dangme West Office', 'Greater Accra Region', 'Shai-Osudoku District', 5.8840459, -0.0941019, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('5e897d40-540f-5f8f-a3a2-eb4c52f6ff48', '0302666576', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('5e897d40-540f-5f8f-a3a2-eb4c52f6ff48', '0299346018', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('5e897d40-540f-5f8f-a3a2-eb4c52f6ff48', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('29b8ffe5-44f0-5fcc-8a40-f6b9969115be', 'Denu Fire Station', 'Volta Region', 'Ketu South Municipal District', 6.0945875, 1.1402513, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('29b8ffe5-44f0-5fcc-8a40-f6b9969115be', '0362026679', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('29b8ffe5-44f0-5fcc-8a40-f6b9969115be', '0299346042', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('29b8ffe5-44f0-5fcc-8a40-f6b9969115be', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('93852571-200d-5b24-afde-7e745548be5f', 'District Fire Station', 'Eastern Region', 'Kwahu Afram Plains North District', 7.0468292, -0.0914016, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('93852571-200d-5b24-afde-7e745548be5f', '0302982062', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('93852571-200d-5b24-afde-7e745548be5f', '0299346041', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('93852571-200d-5b24-afde-7e745548be5f', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('50497487-21d7-51b3-8cf3-a099de367fe9', 'Elmina Fire Station', 'Central Region', 'Komenda/Edina/Eguafo/Abirem Municipal District', 5.0983098, -1.3422902, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('50497487-21d7-51b3-8cf3-a099de367fe9', '0332132902', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('50497487-21d7-51b3-8cf3-a099de367fe9', '0299340499', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('50497487-21d7-51b3-8cf3-a099de367fe9', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('c9c871b5-7fae-5287-b80d-4bebf1cdb124', 'Fire Brigade', 'Eastern Region', 'Asuogyaman District', 6.2783268, 0.0522497, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('c9c871b5-7fae-5287-b80d-4bebf1cdb124', '0302982062', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('c9c871b5-7fae-5287-b80d-4bebf1cdb124', '0299346041', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('c9c871b5-7fae-5287-b80d-4bebf1cdb124', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('57a4acf1-213d-5e51-ba21-2fc45ae4164d', 'Fire Service', 'Ashanti Region', 'Sekyere East District', 6.8520077, -1.3976208, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('57a4acf1-213d-5e51-ba21-2fc45ae4164d', '0322022221', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('57a4acf1-213d-5e51-ba21-2fc45ae4164d', '0299346044', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('57a4acf1-213d-5e51-ba21-2fc45ae4164d', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('fa20afc9-8533-5b75-83aa-17e2c2872158', 'Fire Service Department', 'Bono Region', 'Sunyani Municipal District', 7.3329837, -2.3310411, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('fa20afc9-8533-5b75-83aa-17e2c2872158', '0352027129', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('fa20afc9-8533-5b75-83aa-17e2c2872158', '0299340249', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('fa20afc9-8533-5b75-83aa-17e2c2872158', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('e6aca68d-be89-51dd-8a84-e1abfb5e8dc1', 'Fire Service Station', 'Western North Region', 'Bibiani Anhwiaso Bekwai Municipal District', 6.4559864, -2.3198482, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('e6aca68d-be89-51dd-8a84-e1abfb5e8dc1', '0312193521', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('e6aca68d-be89-51dd-8a84-e1abfb5e8dc1', '0299346040', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('e6aca68d-be89-51dd-8a84-e1abfb5e8dc1', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('9adf636e-d2ac-5a05-9133-2a35202775be', 'Fire service Regional Headquarters', 'Central Region', 'Cape Coast Metropolitan District', 5.1257637, -1.269278, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('9adf636e-d2ac-5a05-9133-2a35202775be', '0332132902', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('9adf636e-d2ac-5a05-9133-2a35202775be', '0299340499', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('9adf636e-d2ac-5a05-9133-2a35202775be', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('807ecfe9-db23-5d30-a8c1-248f15f2929a', 'Fire station', 'Greater Accra Region', 'Ashaiman Municipal District', 5.6844494, -0.0262132, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('807ecfe9-db23-5d30-a8c1-248f15f2929a', '0302666576', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('807ecfe9-db23-5d30-a8c1-248f15f2929a', '0299346018', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('807ecfe9-db23-5d30-a8c1-248f15f2929a', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('fdecd240-f75d-582b-a935-bd6d7e05c12b', 'Ghana Fire Service', 'Ahafo Region', 'Asunafo North Municipal District', 6.808575, -2.5159709, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('fdecd240-f75d-582b-a935-bd6d7e05c12b', '0352027129', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('fdecd240-f75d-582b-a935-bd6d7e05c12b', '0299340249', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('fdecd240-f75d-582b-a935-bd6d7e05c12b', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('8a4010c1-559e-5149-b12b-594c8b863beb', 'Ghana Fire Service', 'Greater Accra Region', 'Ayawaso Central Municipal District', 5.5698415, -0.2143746, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('8a4010c1-559e-5149-b12b-594c8b863beb', '0302666576', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('8a4010c1-559e-5149-b12b-594c8b863beb', '0299346018', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('8a4010c1-559e-5149-b12b-594c8b863beb', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('0c46c6a6-d09d-580a-9445-d1f55511f4d6', 'Ghana Fire Service', 'Greater Accra Region', 'Ledzokuku Municipal District', 5.6111099, -0.1025317, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('0c46c6a6-d09d-580a-9445-d1f55511f4d6', '0302666576', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('0c46c6a6-d09d-580a-9445-d1f55511f4d6', '0299346018', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('0c46c6a6-d09d-580a-9445-d1f55511f4d6', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('088d8b60-5f1b-55fe-bbf1-fbc013b82f6b', 'Ghana Fire Service', 'Volta Region', 'South Dayi District', 6.5345472, 0.2306607, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('088d8b60-5f1b-55fe-bbf1-fbc013b82f6b', '0362026679', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('088d8b60-5f1b-55fe-bbf1-fbc013b82f6b', '0299346042', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('088d8b60-5f1b-55fe-bbf1-fbc013b82f6b', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('89ade940-437a-5d1c-b8dd-ecfde9c32f56', 'Ghana Fire Service (UW/R Head Qaurters)', 'Upper West Region', 'Wa Municipal District', 10.0534606, -2.534765, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('89ade940-437a-5d1c-b8dd-ecfde9c32f56', '0392022389', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('89ade940-437a-5d1c-b8dd-ecfde9c32f56', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('4c2e2b1c-51b1-57a6-8280-ca31a2c068b6', 'Ghana Fire Service Ashiaman', 'Greater Accra Region', 'Ashaiman Municipal District', 5.6918669, -0.0257811, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('4c2e2b1c-51b1-57a6-8280-ca31a2c068b6', '0302666576', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('4c2e2b1c-51b1-57a6-8280-ca31a2c068b6', '0299346018', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('4c2e2b1c-51b1-57a6-8280-ca31a2c068b6', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('dbe660ab-637d-53c9-94eb-c3efe3805c08', 'Ghana National Fire Service', 'Eastern Region', 'New Juaben South Municipal District', 6.0933875, -0.2612821, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('dbe660ab-637d-53c9-94eb-c3efe3805c08', '0302982062', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('dbe660ab-637d-53c9-94eb-c3efe3805c08', '0299346041', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('dbe660ab-637d-53c9-94eb-c3efe3805c08', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('f06a90f7-c554-5e0b-82fb-a386f4b84a03', 'Ghana National Fire Service', 'Eastern Region', 'Birim South District', 5.8495069, -0.9940339, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('f06a90f7-c554-5e0b-82fb-a386f4b84a03', '0302982062', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('f06a90f7-c554-5e0b-82fb-a386f4b84a03', '0299346041', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('f06a90f7-c554-5e0b-82fb-a386f4b84a03', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('68295ff5-aa1d-57c0-ae57-05a03722b5f5', 'Ghana National Fire Service', 'Greater Accra Region', 'La-Nkwantanang-Madina Municipal District', 5.682055, -0.1721383, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('68295ff5-aa1d-57c0-ae57-05a03722b5f5', '0302666576', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('68295ff5-aa1d-57c0-ae57-05a03722b5f5', '0299346018', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('68295ff5-aa1d-57c0-ae57-05a03722b5f5', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('67b2fbd0-7d0e-5a56-a2a3-bcd662423487', 'Ghana National Fire Service', 'Northern Region', 'Tamale Metropolitan District', 9.4038728, -0.8701066, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('67b2fbd0-7d0e-5a56-a2a3-bcd662423487', '0299346046', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('67b2fbd0-7d0e-5a56-a2a3-bcd662423487', '0322022864', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('67b2fbd0-7d0e-5a56-a2a3-bcd662423487', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('7fea0bc7-f545-570f-8bcf-d0a9f878aeaf', 'Ghana National Fire Service', 'Western Region', 'Sekondi Takoradi Metropolitan District', 4.9295697, -1.7479607, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('7fea0bc7-f545-570f-8bcf-d0a9f878aeaf', '0312193521', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('7fea0bc7-f545-570f-8bcf-d0a9f878aeaf', '0299346040', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('7fea0bc7-f545-570f-8bcf-d0a9f878aeaf', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('d7731770-188d-58fd-8b56-308e7050b199', 'Ghana National Fire Service', 'Ashanti Region', 'Kwabre East Municipal District', 6.7867193, -1.5675943, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('d7731770-188d-58fd-8b56-308e7050b199', '0322022221', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('d7731770-188d-58fd-8b56-308e7050b199', '0299346044', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('d7731770-188d-58fd-8b56-308e7050b199', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('5a9eb3f3-efcb-5614-958a-27689e58d0fd', 'Ghana National Fire Service', 'Upper East Region', 'Unknown District', 10.7878408, -0.8421121, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('5a9eb3f3-efcb-5614-958a-27689e58d0fd', '0382022277', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('5a9eb3f3-efcb-5614-958a-27689e58d0fd', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('5415673a-86c2-56e0-90d6-71e39883871d', 'Ghana National Fire Service', 'Central Region', 'Effutu Municipal District', 5.3824871, -0.6415578, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('5415673a-86c2-56e0-90d6-71e39883871d', '0332132902', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('5415673a-86c2-56e0-90d6-71e39883871d', '0299340499', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('5415673a-86c2-56e0-90d6-71e39883871d', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('3c51265e-7d1f-5081-b23c-c8d702f22534', 'Ghana National Fire Service ( Techiman)', 'Bono East Region', 'Techiman Municipal District', 7.5798996, -1.9414318, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('3c51265e-7d1f-5081-b23c-c8d702f22534', '0352027129', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('3c51265e-7d1f-5081-b23c-c8d702f22534', '0299340249', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('3c51265e-7d1f-5081-b23c-c8d702f22534', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('938e1940-c8d1-5b87-9246-c81854c686cd', 'Ghana National Fire Service Enchi', 'Western North Region', 'Aowin Municipal District', 5.821584, -2.8232395, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('938e1940-c8d1-5b87-9246-c81854c686cd', '0312193521', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('938e1940-c8d1-5b87-9246-c81854c686cd', '0299346040', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('938e1940-c8d1-5b87-9246-c81854c686cd', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('8ed4d9a2-e0f3-58b5-b587-c82cf9fceb6f', 'Ghana National Fire Service Headquarters', 'Greater Accra Region', 'La-Dade-Kotopon Municipal District', 5.5696908, -0.1849408, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('8ed4d9a2-e0f3-58b5-b587-c82cf9fceb6f', '0302666576', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('8ed4d9a2-e0f3-58b5-b587-c82cf9fceb6f', '0299346018', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('8ed4d9a2-e0f3-58b5-b587-c82cf9fceb6f', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('77e1f94d-aa44-598b-9d9e-61838309a5f2', 'Ghana National Fire Service Office Hohoe', 'Volta Region', 'Hohoe Municipal District', 7.1697175, 0.4778195, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('77e1f94d-aa44-598b-9d9e-61838309a5f2', '0362026679', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('77e1f94d-aa44-598b-9d9e-61838309a5f2', '0299346042', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('77e1f94d-aa44-598b-9d9e-61838309a5f2', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('f112437a-6983-5eb2-a0c6-c4040c381d6b', 'Ghana National Fire Service: Wassa Akropong', 'Western Region', 'Wassa Amenfi East Municipal District', 5.7832259, -2.0854927, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('f112437a-6983-5eb2-a0c6-c4040c381d6b', '0312193521', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('f112437a-6983-5eb2-a0c6-c4040c381d6b', '0299346040', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('f112437a-6983-5eb2-a0c6-c4040c381d6b', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('0d47a996-3e7a-5793-a109-1172a99a5c8b', 'Ghana National Fire Station, Battor', 'Volta Region', 'North Tongu District', 6.0668599, 0.4014603, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('0d47a996-3e7a-5793-a109-1172a99a5c8b', '0362026679', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('0d47a996-3e7a-5793-a109-1172a99a5c8b', '0299346042', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('0d47a996-3e7a-5793-a109-1172a99a5c8b', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('a1b144d3-297b-56fa-902c-a02e58ea10c0', 'Ghana National Fire and Rescue Service', 'Savannah Region', 'West Gonja Municipal District', 9.0720023, -1.8122543, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('a1b144d3-297b-56fa-902c-a02e58ea10c0', '0299346046', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('a1b144d3-297b-56fa-902c-a02e58ea10c0', '0322022864', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('a1b144d3-297b-56fa-902c-a02e58ea10c0', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('91760762-0a8f-5ee4-949f-ad46bd31a12e', 'Ghanal Fire Service', 'Central Region', 'Twifo Atti Morkwa District', 5.599413, -1.543162, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('91760762-0a8f-5ee4-949f-ad46bd31a12e', '0332132902', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('91760762-0a8f-5ee4-949f-ad46bd31a12e', '0299340499', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('91760762-0a8f-5ee4-949f-ad46bd31a12e', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('bdf65a4f-582b-5f65-8815-81d5ca11dac2', 'Industrial Area Fire Station', 'Greater Accra Region', 'Accra Metropolitan District', 5.5649396, -0.2252361, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('bdf65a4f-582b-5f65-8815-81d5ca11dac2', '0302666576', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('bdf65a4f-582b-5f65-8815-81d5ca11dac2', '0299346018', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('bdf65a4f-582b-5f65-8815-81d5ca11dac2', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('e49d0bb5-53ee-5b4a-b4a5-2ffeed0fa1bd', 'KNUST Fire Service Station', 'Ashanti Region', 'Oforikrom Municipal District', 6.6847456, -1.5744027, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('e49d0bb5-53ee-5b4a-b4a5-2ffeed0fa1bd', '0322022221', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('e49d0bb5-53ee-5b4a-b4a5-2ffeed0fa1bd', '0299346044', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('e49d0bb5-53ee-5b4a-b4a5-2ffeed0fa1bd', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('597b7954-ce22-55c4-9f59-e25dbfa8ef69', 'Komenda Fire station', 'Central Region', 'Komenda/Edina/Eguafo/Abirem Municipal District', 5.0556936, -1.4952523, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('597b7954-ce22-55c4-9f59-e25dbfa8ef69', '0332132902', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('597b7954-ce22-55c4-9f59-e25dbfa8ef69', '0299340499', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('597b7954-ce22-55c4-9f59-e25dbfa8ef69', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('c915a19d-ddd9-5bc2-b15a-aee9e6554c75', 'Kotoku Fire Station', 'Greater Accra Region', 'Ga West Municipal District', 5.7359967, -0.3599341, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('c915a19d-ddd9-5bc2-b15a-aee9e6554c75', '0302666576', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('c915a19d-ddd9-5bc2-b15a-aee9e6554c75', '0299346018', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('c915a19d-ddd9-5bc2-b15a-aee9e6554c75', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('e59a8ca8-44c2-507c-82f5-9e8bce6a23f2', 'Manhyia Fire Station', 'Ashanti Region', 'Asokore-Mampong Municipal District', 6.7028942, -1.6141175, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('e59a8ca8-44c2-507c-82f5-9e8bce6a23f2', '0322022221', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('e59a8ca8-44c2-507c-82f5-9e8bce6a23f2', '0299346044', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('e59a8ca8-44c2-507c-82f5-9e8bce6a23f2', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('529ce7e0-fe5a-5e84-90dc-48f44946ce41', 'Metro Fire Station, Adum -Kumasi', 'Ashanti Region', 'Kumasi Metropolitan District', 6.6860849, -1.623289, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('529ce7e0-fe5a-5e84-90dc-48f44946ce41', '0322022221', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('529ce7e0-fe5a-5e84-90dc-48f44946ce41', '0299346044', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('529ce7e0-fe5a-5e84-90dc-48f44946ce41', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('fb1faf17-1052-523f-b3c5-a92a72498f1c', 'Municipal Fire Station', 'Upper West Region', 'Lawra Municipal District', 10.6458546, -2.8889195, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('fb1faf17-1052-523f-b3c5-a92a72498f1c', '0392022389', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('fb1faf17-1052-523f-b3c5-a92a72498f1c', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('f9e8ae9e-557e-5934-974c-8e0e296c76e9', 'Navrongo Fire Station', 'Upper East Region', 'Kassena-Nankana Municipal District', 10.8960777, -1.089252, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('f9e8ae9e-557e-5934-974c-8e0e296c76e9', '0382022277', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('f9e8ae9e-557e-5934-974c-8e0e296c76e9', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('94a494a6-06d6-5032-98b8-679f1421557d', 'Nkwanta fire service post', 'Oti Region', 'Nkwanta South District', 8.2568687, 0.5231755, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('94a494a6-06d6-5032-98b8-679f1421557d', '0362026679', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('94a494a6-06d6-5032-98b8-679f1421557d', '0299346042', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('94a494a6-06d6-5032-98b8-679f1421557d', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('20b53022-86de-5c40-a3d5-86c112ae6a3c', 'Shama Fire Service', 'Western Region', 'Shama District', 5.0137566, -1.642328, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('20b53022-86de-5c40-a3d5-86c112ae6a3c', '0312193521', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('20b53022-86de-5c40-a3d5-86c112ae6a3c', '0299346040', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('20b53022-86de-5c40-a3d5-86c112ae6a3c', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('2365e92c-6618-5f58-816f-ffba069655d8', 'Tarkwa Fire Station', 'Western Region', 'Tarkwa-Nsuaem Municipal District', 5.3028806, -1.9959644, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('2365e92c-6618-5f58-816f-ffba069655d8', '0312193521', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('2365e92c-6618-5f58-816f-ffba069655d8', '0299346040', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('2365e92c-6618-5f58-816f-ffba069655d8', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('5bdf3a45-4fb7-5031-9654-b50ce6a514d9', 'Tema Industrial Area Fire Station', 'Greater Accra Region', 'Tema Metropolitan District', 5.6656385, 0.0001651, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('5bdf3a45-4fb7-5031-9654-b50ce6a514d9', '0302666576', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('5bdf3a45-4fb7-5031-9654-b50ce6a514d9', '0299346018', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('5bdf3a45-4fb7-5031-9654-b50ce6a514d9', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('1367e3ff-acfe-5b56-bad9-53af9696ca3a', 'UCC Fire Service Station', 'Central Region', 'Cape Coast Metropolitan District', 5.1055128, -1.2799135, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('1367e3ff-acfe-5b56-bad9-53af9696ca3a', '0332132902', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('1367e3ff-acfe-5b56-bad9-53af9696ca3a', '0299340499', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('1367e3ff-acfe-5b56-bad9-53af9696ca3a', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('57533584-e092-5ed6-9f51-7b80c1eceb34', 'University Fire Station Legon', 'Greater Accra Region', 'Ayawaso West Municipal District', 5.6484568, -0.1812207, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('57533584-e092-5ed6-9f51-7b80c1eceb34', '0302666576', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('57533584-e092-5ed6-9f51-7b80c1eceb34', '0299346018', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('57533584-e092-5ed6-9f51-7b80c1eceb34', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('a6f49d3d-1339-57e3-979e-0bc56dabff0e', 'VRA Fire Station', 'Eastern Region', 'Yilo-Krobo Municipal District', 6.0953077, 0.1148369, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('a6f49d3d-1339-57e3-979e-0bc56dabff0e', '0302982062', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('a6f49d3d-1339-57e3-979e-0bc56dabff0e', '0299346041', 0.5, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('a6f49d3d-1339-57e3-979e-0bc56dabff0e', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('2a075c17-5692-5d97-8428-57f8ef066371', 'Wa Fire Station', 'Upper West Region', 'Wa Municipal District', 10.0622441, -2.4979385, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('2a075c17-5692-5d97-8428-57f8ef066371', '0392022389', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('2a075c17-5692-5d97-8428-57f8ef066371', '192', 0.1, true);

INSERT INTO stations (id, name, region, district, lat, lng, active) VALUES
  ('a935538f-a0c1-5123-bfe8-da38b85feb84', 'fire service station', 'Upper East Region', 'Pusiga District', 11.0820273, -0.1232131, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('a935538f-a0c1-5123-bfe8-da38b85feb84', '0382022277', 1.0, true);
INSERT INTO station_contacts (station_id, phone, response_rate, active) VALUES ('a935538f-a0c1-5123-bfe8-da38b85feb84', '192', 0.1, true);

COMMIT;
