-- Generated by app/scripts/build-safety-content-seed.mjs. Do not hand-edit.
-- Source of truth: app/src/data/safety-content.bundled.json
INSERT INTO safety_content (
    slug, category, subcategory, title, summary, body,
    steps, tags, contextual_trigger, sources, content_hash,
    review_state, reviewer_name, reviewer_credential, last_reviewed, reviewed_content_hash
) VALUES (
    'hazard-cooking',
    'hazard',
    'cooking',
    'Cooking Fire Safety',
    'Placeholder — replaced in Task 7.',
    'Placeholder body. Replaced with sourced content in Task 7.',
    '[]'::jsonb,
    '["cooking"]'::jsonb,
    NULL,
    '[{"title":"Placeholder","publisher":"Placeholder","year":"2026","url":"https://example.org","unverified":true}]'::jsonb,
    'ef7c103f0e356c0a83ad3ab195ed90c7343a17bf5bb4a7d71837f6f581d3e55d',
    'draft',
    NULL,           -- reviewer_name
    NULL,     -- reviewer_credential
    NULL,
    NULL
) ON CONFLICT (slug) DO UPDATE SET
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    body = EXCLUDED.body,
    steps = EXCLUDED.steps,
    tags = EXCLUDED.tags,
    contextual_trigger = EXCLUDED.contextual_trigger,
    sources = EXCLUDED.sources,
    content_hash = EXCLUDED.content_hash,
    review_state = EXCLUDED.review_state,
    reviewer_name = EXCLUDED.reviewer_name,
    reviewer_credential = EXCLUDED.reviewer_credential,
    last_reviewed = EXCLUDED.last_reviewed,
    reviewed_content_hash = EXCLUDED.reviewed_content_hash;

INSERT INTO safety_content (
    slug, category, subcategory, title, summary, body,
    steps, tags, contextual_trigger, sources, content_hash,
    review_state, reviewer_name, reviewer_credential, last_reviewed, reviewed_content_hash
) VALUES (
    'firstaid-burns',
    'first_aid',
    'burns',
    'Burns',
    'Placeholder — replaced in Task 7.',
    'Placeholder body. Replaced with sourced content in Task 7.',
    '[{"title":"Placeholder step","body":"Replaced in Task 7."}]'::jsonb,
    '["burns"]'::jsonb,
    NULL,
    '[{"title":"Placeholder","publisher":"Placeholder","year":"2026","url":"https://example.org","unverified":true}]'::jsonb,
    'b76f2565d98c0f166f98595c146e5d3e2e5783b70eca7f52bb05ac6628afba75',
    'draft',
    NULL,           -- reviewer_name
    NULL,     -- reviewer_credential
    NULL,
    NULL
) ON CONFLICT (slug) DO UPDATE SET
    category = EXCLUDED.category,
    subcategory = EXCLUDED.subcategory,
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    body = EXCLUDED.body,
    steps = EXCLUDED.steps,
    tags = EXCLUDED.tags,
    contextual_trigger = EXCLUDED.contextual_trigger,
    sources = EXCLUDED.sources,
    content_hash = EXCLUDED.content_hash,
    review_state = EXCLUDED.review_state,
    reviewer_name = EXCLUDED.reviewer_name,
    reviewer_credential = EXCLUDED.reviewer_credential,
    last_reviewed = EXCLUDED.last_reviewed,
    reviewed_content_hash = EXCLUDED.reviewed_content_hash;
